#!/bin/bash

# requirements:
#   edk2-ovmf
#   qemu-main
#   kvm : for kvm support, enable it too
#   samba
#   cifs-utils
#   openssh

# naming-scheme:
# function names startin with _ are helping functions ( not used in main() ).
# local variables are named in snake case
# array namerefs use ___ to avoid cyclic reference

_get_dir_vm()
{
  declare -r dir_type="$1"
  case "$dir_type" in
    ovmf)
      echo "/usr/share/edk2-ovmf/x64"
      ;;
    iso)
      echo "${HOME}/Downloads/isos"
      ;;
    config)
      echo "${HOME}/.config/vm"
      ;;
    image)
      echo "${HOME}/.config/vm/images"
      ;;
    backup)
      echo "${HOME}/.config/vm/backup"
      ;;
    ovmf_var)
      echo "${HOME}/.config/vm/ovmf"
      ;;
    samba)
      echo "${HOME}/Shared"
      ;;
  esac
}

################################################################
##
## Bash-Completion
##
################################################################

_completion_handler()
{
  declare -r vm_config_dir=$(_get_dir_vm "config")
  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r vm_backup_dir=$(_get_dir_vm "backup")
  declare -r vm_samba_shared_dir=$(_get_dir_vm "samba")
  declare -r vm_ovmf_var_for_images_dir=$(_get_dir_vm "ovmf_var")
  declare -r vm_iso_dir=$(_get_dir_vm "iso")
  declare -r vm_ovmf_dir=$(_get_dir_vm "ovmf")

  local cur prev subcmd
  if type -t _init_completion > /dev/null; then
    _init_completion -n = || return
  else
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"
  fi
  subcmd="${COMP_WORDS[1]}"

  # list of options for each command
  local initialize_options=()
  for file in "$vm_iso_dir/"*; do
    if [[ -f "$file" ]]; then
      initialize_options+=("$(basename "$file")")
    fi
  done

  local run_vm_options=()
  for file in "$vm_image_dir/"*; do
    if [[ -f "$file" ]]; then
      run_vm_options+=("$(basename "$file")")
    fi
  done

  local copy_vm_options=("${run_vm_options[@]}")
  local backup_vm_options=("${run_vm_options[@]}")
  local delete_vm_options=("${run_vm_options[@]}")

  local active_vm_options=()
  while read -r image_name_pid; do
    active_vm_options+=("$image_name_pid")
  done < <(pgrep -a qemu | sed "s|^\([0-9]*\)\s\(.*\)${vm_image_dir}/\(\S*\).*|\3|;t;d")

  local kill_vm_options=("${active_vm_options[@]}")

  local kill_vm_pid_options=()
  while read -r pid; do
    kill_vm_pid_options+=("$pid")
  done < <(pgrep -a qemu | sed "s|^\([0-9]*\)\s\(.*\)${vm_image_dir}/\(\S*\).*|\1|;t;d")

  local existing_config_options=()
  while read -r pid; do
    existing_config_options+=("$pid")
  done < <(sed "s|.*\[\(.*\)\].*|\1|;t;d" "${vm_config_dir}/config.vm")

  local config_args="--boot_type --ssh_port --vnc_port --ram --cpus --cores --ssh_user_name"
  local initialize_args="${config_args} --iso_name --image_size"

  # complete options for vm command
  case "$prev" in
    vm | ./vm)
      mapfile -t COMPREPLY < <(compgen -W "--generate_image --initialize --new --run --delete --backup --list --ssh --vnc --smb-follow-symlink --kill --config --establish_dirs --install --help" -- "$cur")
      ;;
    --initialize | -n | --new | --setup)
      mapfile -t COMPREPLY < <(compgen -W "${run_vm_options[*]}" -- "$cur")
      ;;
    -x | --xerox | --copy | -m | --move)
      mapfile -t COMPREPLY < <(compgen -W "${copy_vm_options[*]}" -- "$cur")
      ;;
    -r | --run)
      mapfile -t COMPREPLY < <(compgen -W "${run_vm_options[*]}" -- "$cur")
      ;;
    -d | --delete)
      mapfile -t COMPREPLY < <(compgen -W "${delete_vm_options[*]}" -- "$cur")
      ;;
    -l | --list)
      mapfile -t COMPREPLY < <(compgen -W "--active --all" -- "$cur")
      ;;
    -b | --backup)
      mapfile -t COMPREPLY < <(compgen -W "--config ${backup_vm_options[*]}" -- "$cur")
      ;;
    -s | --ssh)
      mapfile -t COMPREPLY < <(compgen -W "${active_vm_options[*]}" -- "$cur")
      ;;
    -v | --vnc)
      mapfile -t COMPREPLY < <(compgen -W "${active_vm_options[*]}" -- "$cur")
      ;;
    -k | --kill)
      mapfile -t COMPREPLY < <(compgen -W "--all --pid ${kill_vm_options[*]}" -- "$cur")
      ;;
    -e | --establish_dirs)
      mapfile -t COMPREPLY < <(compgen -W "--remove" -- "$cur")
      ;;
    -z | --install)
      mapfile -t COMPREPLY < <(compgen -W "--uninstall" -- "$cur")
      ;;
    -c | --config)
      case "$subcmd" in
        -c | --config)
          mapfile -t COMPREPLY < <(compgen -W "--delete --modify --print --open ${run_vm_options[*]}" -- "$cur")
          ;;
        -b | --backup)
          mapfile -t COMPREPLY < <(compgen -W "${existing_config_options[*]}" -- "$cur")
          ;;
      esac
      ;;
    *)
      case "$subcmd" in
        -i | --initialize | -n | --new | --setup | -c | --config)
          case "$prev" in
            --iso_name)
              mapfile -t COMPREPLY < <(compgen -W "${initialize_options[*]}" -- "$cur")
              ;;
            --boot_type)
              mapfile -t COMPREPLY < <(compgen -W "legacy efi" -- "$cur")
              ;;
            -d | --delete | -m | --modify | -p | --print)
              mapfile -t COMPREPLY < <(compgen -W "${existing_config_options[*]}" -- "$cur")
              ;;
            --ssh_user_name)
              mapfile -t COMPREPLY < <(compgen -W "$USER" -- "$cur")
              ;;
            *)
              case "$subcmd" in
                -i | --initialize | -n | --new | --setup)
                  mapfile -t COMPREPLY < <(compgen -W "$initialize_args" -- "$cur")
                  ;;
                -c | --config)
                  mapfile -t COMPREPLY < <(compgen -W "$config_args" -- "$cur")
                  ;;
              esac
              ;;
          esac
          ;;
        -k | --kill)
          if [[ $prev == "-p" || $prev == "--pid" ]]; then
            mapfile -t COMPREPLY < <(compgen -W "${kill_vm_pid_options[*]}" -- "$cur")
          fi
          ;;
        *) ;;
      esac
      ;;
  esac
}

# just source completion function when script is sourced
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  complete -F _completion_handler vm
  complete -F _completion_handler ./vm
  return 0
fi

setup_bash_completion_vm()
{
  {
    typeset -f _get_dir_vm
    typeset -f _completion_handler
    echo "complete -F _completion_handler vm"
  } >> /etc/bash_completion.d/vm.bash_completion

  echo "$(basename "$0"): modified file: /etc/bash_completion.d/vm.bash_completion"
}

################################################################
##
## Script
##
################################################################

establish_dirs_vm()
{
  declare -r remove_dirs="$2"

  declare -r vm_config_dir=$(_get_dir_vm "config")
  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r vm_backup_dir=$(_get_dir_vm "backup")
  declare -r vm_ovmf_var_for_images_dir=$(_get_dir_vm "ovmf_var")
  declare -r vm_samba_shared_dir=$(_get_dir_vm "samba")

  mkdir -pv "$vm_config_dir" "$vm_backup_dir" "$vm_image_dir"
  mkdir -pv "$vm_samba_shared_dir" "$vm_ovmf_var_for_images_dir"

  if [[ "$remove_dirs" == "-r" || "$remove_dirs" == "--remove" ]]; then
    mkdir -pv "$vm_backup_dir"/images "$vm_backup_dir"/ovmf
    touch "${vm_config_dir}/config.vm"
  fi
}

install_vm()
{
  declare -r uninstall="$2"
  if [[ "$uninstall" == "-u" || "$uninstall" == "--uninstall" ]]; then
    establish_dirs_vm
    mkdir -pv "$HOME/.local/scripts"
    export PATH="${PATH}:${HOME}/.local/scripts"

    # shellcheck source=/dev/null
    source "${HOME}/.local/scripts/vm"

    {
      echo "export PATH=\"\$PATH\":\"\$HOME\"/.local/scripts"
      echo "source \"\$HOME\"/.local/scripts/vm"
    } >> "${HOME}/.bashrc"
  else
    rm -rv "$0"
    sed -i "|^source.*/.local/scripts/vm|d"
  fi
}

_trim_and_lower_case_vm()
{
  local string
  string="$1"
  string=$(echo -e "${string}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
  string=${string,,}
  echo "$string"
}

_read_config_vm()
{
  declare -n ____vm_image_config="$1"
  declare -r do_not_return_defaults="$2"

  if [[ -n "${____vm_image_config[vm_config_path]}" ]]; then
    declare -r vm_config_path="${____vm_image_config[vm_config_path]}"
  else
    declare -r vm_config_path="$(_get_dir_vm "config")/config.vm"
  fi

  declare -i image_config_found=0

  while read -r line; do

    config_setting[idx]=$(echo -e "${config_setting[idx]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
    config_setting[idx]=${config_setting[idx],,}

    local edited_line
    edited_line=$(_trim_and_lower_case_vm "$line")

    if [[ "$edited_line" == "[${____vm_image_config[image_name]}]" ]]; then
      image_config_found=1
    elif [[ "$image_config_found" -eq 1 && "$edited_line" =~ ^"[".*"]"$ ]]; then
      break
    fi

    if [[ $image_config_found -eq 1 ]]; then

      IFS="=" read -ra config_setting <<< "$line"

      for ((idx = 0; idx < ${#config_setting[@]}; idx++)); do
        config_setting[idx]=$(_trim_and_lower_case_vm "${config_setting[idx]}")
      done

      if [[ ${config_setting[0]} == "boot_type" && -z ${____vm_image_config[boot_type]} ]]; then
        ____vm_image_config[boot_type]="${config_setting[1]}"
      fi

      if [[ ${config_setting[0]} == "ssh_port" && -z ${____vm_image_config[ssh_port]} ]]; then
        ____vm_image_config[ssh_port]="${config_setting[1]}"
      fi

      if [[ ${config_setting[0]} == "vnc_port" && -z ${____vm_image_config[vnc_port]} ]]; then
        ____vm_image_config[vnc_port]="${config_setting[1]}"
      fi

      if [[ ${config_setting[0]} == "ram" && -z ${____vm_image_config[ram]} ]]; then
        ____vm_image_config[ram]="${config_setting[1]}"
      fi

      if [[ ${config_setting[0]} == "cpus" && -z ${____vm_image_config[cpus]} ]]; then
        ____vm_image_config[cpus]="${config_setting[1]}"
      fi

      if [[ ${config_setting[0]} == "cores" && -z ${____vm_image_config[cores]} ]]; then
        ____vm_image_config[cores]="${config_setting[1]}"
      fi

      if [[ ${config_setting[0]} == "ssh_user_name" && -z ${____vm_image_config[ssh_user_name]} ]]; then
        ____vm_image_config[ssh_user_name]="${config_setting[1]}"
      fi

    fi

  done < "${vm_config_path}"

  if [[ -z "$do_not_return_defaults" ]]; then
    if [[ -z "${____vm_image_config[boot_type]}" ]]; then
      echo "$(basename "$0"): config: boot_type for ${____vm_image_config[image_name]} not found. using efi"
      ____vm_image_config[boot_type]="efi"
    fi

    if [[ -z "${____vm_image_config[ssh_port]}" ]]; then
      echo "$(basename "$0"): config: ssh_port for ${____vm_image_config[image_name]} not found. using 2222"
      ____vm_image_config[ssh_port]="2222"
    fi

    if [[ -z "${____vm_image_config[vnc_port]}" ]]; then
      echo "$(basename "$0"): config: vnc_port for ${____vm_image_config[image_name]} not found. using 5900"
      ____vm_image_config[vnc_port]="5900"
    fi

    if [[ -z "${____vm_image_config[ram]}" ]]; then
      echo "$(basename "$0"): config: ram for ${____vm_image_config[image_name]} not found. using 4GB"
      ____vm_image_config[ram]="4"
    fi

    if [[ -z "${____vm_image_config[cpus]}" ]]; then
      echo "$(basename "$0"): config: cpus for ${____vm_image_config[image_name]} not found. using 4"
      ____vm_image_config[cpus]="4"
    fi

    if [[ -z "${____vm_image_config[cores]}" ]]; then
      echo "$(basename "$0"): config: cores for ${____vm_image_config[image_name]} not found. using 4"
      ____vm_image_config[cores]="4"
    fi

  fi

  if [[ -n "$3" ]]; then
    echo "${____vm_image_config[@]}"
  fi

  [[ $image_config_found -eq 1 ]] && return 0 || return 1
}

# already existing values in config remain same and cannot be changed
# delete and write again to update those or do it manually
_write_config_vm()
{
  declare -n ___vm_image_config="$1"
  declare -r overwrite_existing="$2"

  if [[ -n "${___vm_image_config[vm_config_path]}" ]]; then
    declare -r vm_config_path="${___vm_image_config[vm_config_path]}"
  else
    declare -r vm_config_path="$(_get_dir_vm "config")/config.vm"
  fi

  if _read_config_vm ___vm_image_config "do_not_return_defaults" &> /dev/null; then
    if [[ -n "$overwrite_existing" ]]; then
      _delete_config_vm "${___vm_image_config[image_name]}" "${___vm_image_config[vm_config_path]}"
    else
      return 1
    fi
  fi

  if [[ -z "${___vm_image_config[boot_type]}" ]]; then
    ___vm_image_config[boot_type]="efi"
  fi

  if [[ -z "${___vm_image_config[ssh_port]}" ]]; then
    ___vm_image_config[ssh_port]="2222"
  fi

  if [[ -z "${___vm_image_config[vnc_port]}" ]]; then
    ___vm_image_config[vnc_port]="5900"
  fi

  if [[ -z "${___vm_image_config[ram]}" ]]; then
    ___vm_image_config[ram]="4"
  fi

  if [[ -z "${___vm_image_config[cpus]}" ]]; then
    ___vm_image_config[cpus]="4"
  fi

  if [[ -z "${___vm_image_config[cores]}" ]]; then
    ___vm_image_config[cores]="4"
  fi

  cat >> "${vm_config_path}" << EOF
[${___vm_image_config[image_name]}]
boot_type=${___vm_image_config[boot_type]}
ssh_port=${___vm_image_config[ssh_port]}
vnc_port=${___vm_image_config[vnc_port]}
ram=${___vm_image_config[ram]}
cpus=${___vm_image_config[cpus]}
cores=${___vm_image_config[cores]}
EOF

  if [[ -n "${___vm_image_config[ssh_user_name]}" ]]; then
    echo "ssh_user_name=${___vm_image_config[ssh_user_name]}" >> "${vm_config_path}"
  fi

}

_delete_config_vm()
{
  declare -r image_name="$1"
  if [[ -n "$2" ]]; then
    declare -r vm_config_path="$2"
  else
    declare -r vm_config_path="$(_get_dir_vm "config")/config.vm"
  fi

  declare -i image_config_found=0
  declare -i image_config_start=0
  declare -i image_config_end=0

  while read -r line; do

    local edited_line
    edited_line=$(_trim_and_lower_case_vm "$line")

    if [[ "$edited_line" == "[$image_name]" ]]; then
      image_config_found=1
      image_config_start=$((image_config_end + 1))
    elif [[ "$image_config_found" -eq 1 && "$edited_line" =~ ^"[".*"]"$ ]]; then
      break
    fi

    image_config_end+=1

  done < "${vm_config_path}"

  if [[ $image_config_found -eq 1 ]]; then
    sed -i "${image_config_start},${image_config_end}d" "${vm_config_path}"
    return 0
  fi

  return 1
}

generate_image_vm()
{
  declare -r image_name="$1"
  declare -r image_size="$2"

  if [[ -z "$image_name" ]]; then
    echo "$(basename "$0"): image_name missing"
    return 1
  fi

  declare -r vm_image_dir=$(_get_dir_vm "image")

  if [[ -z "$image_size" ]]; then
    echo "$(basename "$0"): image_size missing, using 20GB"
    qemu-img create -o nocow=on -f qcow2 "$vm_image_dir"/"${image_name:?}" 20G
  else
    qemu-img create -o nocow=on -f qcow2 "$vm_image_dir"/"${image_name:?}" "${image_size}"G
  fi

  echo "$(basename "$0"): created image: ${vm_image_dir}/${image_name}"
}

initialize_vm()
{
  declare -n __vm_image_config="$1"

  declare -r iso_name="${__vm_image_config[iso_name]}"
  declare -r image_name="${__vm_image_config[image_name]}"

  if [[ -z "$image_name" || -z "$iso_name" ]]; then
    echo "$(basename "$0"): image_name or --iso_name missing"
    return 1
  fi

  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r vm_iso_dir=$(_get_dir_vm "iso")
  declare -r vm_ovmf_dir=$(_get_dir_vm "ovmf")
  declare -r vm_ovmf_var_for_images_dir=$(_get_dir_vm "ovmf_var")
  declare -r vm_samba_shared_dir=$(_get_dir_vm "samba")

  # write config
  _write_config_vm __vm_image_config "overwrite"

  # these need to be read after write_config because this fills them
  # with default values for missing ones
  declare -r boot_type="${__vm_image_config[boot_type]}"
  declare -ri ssh_port="${__vm_image_config[ssh_port]}"
  declare -ri vnc_port="${__vm_image_config[vnc_port]}"
  declare -ri ram="${__vm_image_config[ram]}"
  declare -ri cpus="${__vm_image_config[cpus]}"
  declare -ri cores="${__vm_image_config[cores]}"

  if [[ "legacy" == $(_trim_and_lower_case_vm "$boot_type") ]]; then
    qemu-system-x86_64 -enable-kvm -cdrom "${vm_iso_dir}/${iso_name}" -boot order=d -drive file="${vm_image_dir}/${image_name}" -vnc :$((vnc_port - 5900)) -nic user,hostfwd=tcp::"$ssh_port"-:22,smb="$vm_samba_shared_dir" -daemonize -m "$ram"G -smp cores="$cores",cpus="$cpus"
  else
    cp -i "${vm_ovmf_dir}/OVMF_VARS.fd" "${vm_ovmf_var_for_images_dir}/${image_name}.fd"
    qemu-system-x86_64 -enable-kvm -cdrom "${vm_iso_dir}/${iso_name}" -boot order=d -drive file="${vm_image_dir}/${image_name}" -vnc :$((vnc_port - 5900)) -nic user,hostfwd=tcp::"$ssh_port"-:22,smb="$vm_samba_shared_dir" -daemonize -m "$ram"G -smp cores="$cores",cpus="$cpus" -drive if=pflash,format=raw,unit=0,readonly=on,file="${vm_ovmf_dir}/OVMF_CODE.fd" -drive if=pflash,format=raw,unit=1,file="${vm_ovmf_var_for_images_dir}/${image_name}.fd"
  fi

  echo "$(basename "$0"): initialized image: ${vm_image_dir}/${image_name}"
}

setup_vm()
{
  declare -n _vm_image_config="$1"

  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r image_name="${_vm_image_config[image_name]}"
  declare -r image_size="${_vm_image_config[image_size]}"

  generate_image_vm "$image_name" "$image_size"
  initialize_vm _vm_image_config
  echo "$(basename "$0"): setup complete for image: ${vm_image_dir}/${image_name}"
}

delete_vm()
{
  declare -r image_name="$2"

  if [[ -z "$image_name" ]]; then
    echo "$(basename "$0"): image_name missing"
    return 1
  fi

  declare -r remove_backup="$3"

  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r vm_ovmf_var_for_images_dir=$(_get_dir_vm "ovmf_var")

  rm -rv "${vm_image_dir}/${image_name:?}"
  rm -rv "${vm_ovmf_var_for_images_dir}/${image_name:?}.fd"
  _delete_config_vm "$image_name"

  if [[ "$remove_backup" = "-a" || "$remove_backup" = "--all" ]]; then
    declare -r vm_backup_dir=$(_get_dir_vm "backup")
    rm -rv "${vm_backup_dir}/${image_name:?}"
    _delete_config_vm "$image_name" "$vm_backup_dir/config.vm"
  fi
}

backup_vm()
{
  declare -r config_or_image_name="$2"

  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r vm_config_dir=$(_get_dir_vm "config")
  declare -r vm_backup_dir=$(_get_dir_vm "backup")
  declare -r vm_ovmf_var_for_images_dir=$(_get_dir_vm "ovmf_var")

  if [[ "$config_or_image_name" == "-c" || "$config_or_image_name" == "--config" ]]; then
    cp "${vm_config_dir}/config.vm" "${vm_backup_dir}/config.vm"
    echo "$(basename "$0"): backed up config: ${vm_config_dir}/config.vm to ${vm_backup_dir}/config.vm"
  elif [[ -z "$config_or_image_name" ]]; then
    echo "$(basename "$0"): image_name missing"
    return 1
  else
    declare -r image_name="$config_or_image_name"
    cp -i "${vm_image_dir}/${image_name}" "${vm_backup_dir}/images/${image_name}"
    cp -i "${vm_ovmf_var_for_images_dir}/${image_name}.fd" "${vm_backup_dir}/ovmf/${image_name}.fd"
    cp "${vm_config_dir}/config.vm" "${vm_backup_dir}/config.vm"

    echo "$(basename "$0"): backed up image: ${vm_image_dir}/${image_name}"
  fi
}

run_vm()
{
  declare -r image_name="$2"

  if [[ -z "$image_name" ]]; then
    echo "$(basename "$0"): image_name missing"
    return 1
  fi

  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r vm_ovmf_dir=$(_get_dir_vm "ovmf")
  declare -r vm_ovmf_var_for_images_dir=$(_get_dir_vm "ovmf_var")
  declare -r vm_samba_shared_dir=$(_get_dir_vm "samba")

  declare -A ___vm_image_config
  ___vm_image_config[image_name]="$image_name"
  _read_config_vm ___vm_image_config

  declare -r boot_type="${___vm_image_config[boot_type]}"
  declare -ri ssh_port="${___vm_image_config[ssh_port]}"
  declare -ri vnc_port="${___vm_image_config[vnc_port]}"
  declare -ri ram="${___vm_image_config[ram]}"
  declare -ri cpus="${___vm_image_config[cpus]}"
  declare -ri cores="${___vm_image_config[cores]}"

  if [[ "$boot_type" == "legacy" ]]; then
    echo "$(basename "$0"): running image: ${vm_image_dir}/${image_name}"
    qemu-system-x86_64 -enable-kvm -vnc :$((vnc_port - 5900)) -nic user,hostfwd=tcp::"$ssh_port"-:22,smb="$vm_samba_shared_dir" -daemonize -m "$ram"G -smp cores="$cores",cpus="$cpus" "${vm_image_dir}/${image_name}"
  elif [[ "$boot_type" == "efi" ]]; then
    echo "$(basename "$0"): running image: ${vm_image_dir}/${image_name}"
    qemu-system-x86_64 -enable-kvm -vnc :$((vnc_port - 5900)) -nic user,hostfwd=tcp::"$ssh_port"-:22,smb="$vm_samba_shared_dir" -daemonize -m "$ram"G -smp cores="$cores",cpus="$cpus" "${vm_image_dir}/${image_name}" -drive if=pflash,format=raw,readonly=on,file="${vm_ovmf_dir}/OVMF_CODE.fd" -drive if=pflash,format=raw,file="${vm_ovmf_var_for_images_dir}/${image_name}.fd"
  else
    echo "$(basename "$0"): config: error in boot_type for ${image_name}"
  fi
}

# enable symlink support for shared folder
qemu_smb_support_symlink_all_vm()
{
  declare -ra pids=$(pgrep -a smbd | sed "s|^\([0-9]*\)\s/usr/bin/smbd\(.*\)|\1|;t;d")
  local -a confs
  mapfile -t confs < <(pgrep -a smbd | sed "s|^\([0-9]*\)\s/usr/bin/smbd.*\(/tmp/qemu-smb.*$\)\(.*\)|\2|;t;d")

  declare -r smb_config_global="allow insecure wide links = yes"
  declare -r smb_config_qemu="follow symlinks = yes\nwide links = yes\nacl allow execute always = yes"

  declare -i global_config_added=0
  declare -i qemu_config_added=0
  declare -i global_exists=1
  declare -i qemu_exists=1

  declare smb_conf_path

  for ((i = 0; i < ${#pids[@]}; i++)); do
    smb_conf_path="${confs[i]}"
    if [[ -f "$smb_conf_path" ]]; then
      global_exists=$(grep -cx "$smb_config_global" "$smb_conf_path")
      if [ "$global_exists" -eq 0 ]; then
        sed -i "/\[global\]/a ${smb_config_global}" "$smb_conf_path"
        global_config_added=1
      fi

      qemu_exists=$(grep -zPcx "$smb_config_qemu" "$smb_conf_path")
      if [ "$qemu_exists" -eq 0 ]; then
        sed -i "/\[qemu\]/a ${smb_config_qemu}" "$smb_conf_path"
        qemu_config_added=1
      fi

      if [ "$global_config_added" -eq 1 ] || [ "$qemu_config_added" -eq 1 ]; then
        sudo smbcontrol --configfile="${smb_conf_path}" "${pids[i]}" reload-config
      fi

      echo "$(basename "$0"): modified file: ${smb_conf_path}"

      global_config_added=0
      qemu_config_added=0
    fi
  done
}

list_vm()
{
  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r all_vms="$2"

  if [[ "$all_vms" = "-a" || "$all_vms" = "--all" ]]; then
    for file in "${vm_image_dir}/"*; do
      if [[ -f "$file" ]]; then
        basename "$file"
      fi
    done
  elif [[ "$2" = "--active" || -z $2 ]]; then
    pgrep -a qemu | sed "s|^\([0-9]*\)\s\(.*\)${vm_image_dir}/\(\S*\).*|\1 \3|;t;d"
  fi
}

kill_vm()
{
  declare -r option_or_image_name="$2"

  if [[ $option_or_image_name == "-a" || $option_or_image_name == "--all" ]]; then
    killall qemu-system-x86_64
    echo "$(basename "$0"): killed all active qemu vms"
  elif [[ $option_or_image_name == "-p" || $option_or_image_name == "--pid" ]]; then
    declare -r pid="$3"

    if [[ -z "$pid" ]]; then
      echo "$(basename "$0"): pid missing"
      return 1
    fi

    kill -9 "$pid"
    echo "$(basename "$0"): killed vm: ${pid}"
  else
    declare -r image_name="$option_or_image_name"

    if [[ -z "$image_name" ]]; then
      echo "$(basename "$0"): image_name missing"
      return 1
    fi

    declare pid
    declare -r vm_image_dir=$(_get_dir_vm "image")
    pid=$(pgrep -a qemu | sed "s|^\([0-9]*\)\s\(.*\)${vm_image_dir}/${image_name}\(.*\)|\1|;t;d")
    kill -9 "$pid"
    echo "$(basename "$0"): killed vm: ${image_name}"
  fi
}

ssh_vm()
{
  declare -r image_name="$2"

  if [[ -z "$image_name" ]]; then
    echo "$(basename "$0"): image_name missing"
    return 1
  fi

  declare -A ___vm_image_config
  ___vm_image_config[image_name]="$image_name"
  _read_config_vm ___vm_image_config

  declare user_name
  if [[ -n "$3" ]]; then
    user_name="$3"
  elif [[ -n ${___vm_image_config[ssh_user_name]} ]]; then
    user_name=${___vm_image_config[ssh_user_name]}
  else
    user_name=$USER
  fi

  declare -i ssh_port=${___vm_image_config[ssh_port]}

  ssh "$user_name"@localhost -p "$ssh_port"
}

vnc_vm()
{
  declare -r image_name="$2"

  if [[ -z "$image_name" ]]; then
    echo "$(basename "$0"): image_name missing"
    return 1
  fi

  declare -A ___vm_image_config
  ___vm_image_config[image_name]="$image_name"
  _read_config_vm ___vm_image_config

  declare -i vnc_port=${___vm_image_config[vnc_port]}
  vncviewer :"$vnc_port" &> /dev/null &
}

config_vm()
{
  # shellcheck disable=2178
  declare -n __vm_image_config="$1"
  declare -r mode="$3"

  case "$mode" in
    -m | --modify | -d | --delete | -p | --print)
      declare -r image_name="$4"
      vm_image_config[image_name]="$image_name"
      ;;
    *)
      declare -r image_name="$3"
      vm_image_config[image_name]="$image_name"
      ;;
  esac

  if [[ -z "$image_name" ]]; then
    echo "$(basename "$0"): image_name missing"
    return 1
  fi

  case "$mode" in
    -m | --modify)
      if _write_config_vm __vm_image_config "overwrite"; then
        echo "$(basename "$0"): config for $image_name over-written successfully"
      fi
      ;;
    -d | --delete)
      if _delete_config_vm "$image_name"; then
        echo "$(basename "$0"): config for $image_name deleted successfully"
      fi
      ;;
    -o | --open)
      "$EDITOR" "$(_get_dir_vm "config")/config.vm"
      ;;
    -p | --print)
      if _read_config_vm __vm_image_config "do_not_return_defaults"; then
        if [[ -n ${__vm_image_config[image_name]} ]]; then
          echo
          echo "[${__vm_image_config[image_name]}]"
          if [[ -n ${__vm_image_config[boot_type]} ]]; then
            echo "boot_type = ${__vm_image_config[boot_type]}"
          fi
          if [[ -n ${__vm_image_config[ssh_port]} ]]; then
            echo "ssh_port  = ${__vm_image_config[ssh_port]}"
          fi
          if [[ -n ${__vm_image_config[vnc_port]} ]]; then
            echo "vnc_port  = ${__vm_image_config[vnc_port]}"
          fi
          if [[ -n ${__vm_image_config[ram]} ]]; then
            echo "ram       = ${__vm_image_config[ram]}"
          fi
          if [[ -n ${__vm_image_config[cpus]} ]]; then
            echo "cpus      = ${__vm_image_config[cpus]}"
          fi
          if [[ -n ${__vm_image_config[cores]} ]]; then
            echo "cores     = ${__vm_image_config[cores]}"
          fi
        fi
      fi
      ;;
    *)
      if _write_config_vm __vm_image_config; then
        echo "$(basename "$0"): config for $image_name written successfully"
      fi
      ;;
  esac
}

copy_vm()
{
  declare -r source="$2"
  declare -r destination="$3"

  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r vm_ovmf_var_for_images_dir=$(_get_dir_vm "ovmf_var")

  # copy config
  declare -A __vm_image_config
  __vm_image_config[image_name]="$source"
  _read_config_vm __vm_image_config
  __vm_image_config[image_name]="$destination"
  _write_config_vm __vm_image_config

  # copy image
  cp -i "${vm_image_dir}/${source}" "${vm_image_dir}/${destination}"
  if [[ ${__vm_image_config[boot_type]} == "efi" ]]; then
    # copy ovmf var file
    cp -i "${vm_ovmf_var_for_images_dir}/${source}.fd" "${vm_ovmf_var_for_images_dir}/${destination}.fd"
  fi
}

move_vm()
{
  declare -r source="$2"
  declare -r destination="$3"

  declare -r vm_image_dir=$(_get_dir_vm "image")
  declare -r vm_ovmf_var_for_images_dir=$(_get_dir_vm "ovmf_var")

  # move config
  declare -A __vm_image_config
  __vm_image_config[image_name]="$source"
  _read_config_vm __vm_image_config
  _delete_config_vm "${__vm_image_config[image_name]}"
  __vm_image_config[image_name]="$destination"
  _write_config_vm __vm_image_config

  # move image
  mv -v "${vm_image_dir}/${source}" "${vm_image_dir}/${destination}"
  if [[ ${__vm_image_config[boot_type]} == "efi" ]]; then
    # move ovmf var file
    mv -v "${vm_ovmf_var_for_images_dir}/${source}.fd" "${vm_ovmf_var_for_images_dir}/${destination}.fd"
  fi
}

take_config_args_vm()
{
  declare -n _vm_image_config="$1"

  for ((i = 3; i <= "$#"; i++)); do
    next=$((i + 1))
    case "${!i}" in
      --iso_name)
        _vm_image_config[iso_name]="${!next}"
        ;;
      --boot_type)
        _vm_image_config[boot_type]="${!next}"
        ;;
      --ssh_port)
        _vm_image_config[ssh_port]="${!next}"
        ;;
      --vnc_port)
        _vm_image_config[vnc_port]="${!next}"
        ;;
      --ram)
        _vm_image_config[ram]="${!next}"
        ;;
      --cores)
        _vm_image_config[cores]="${!next}"
        ;;
      --cpus)
        _vm_image_config[cpus]="${!next}"
        ;;
      --image_size)
        _vm_image_config[image_size]="${!next}"
        ;;
      --ssh_user_name)
        _vm_image_config[ssh_user_name]="${!next}"
        ;;
      *) ;;
    esac
  done
}

help_vm()
{
  declare -r full_help="$2"
  declare -r tldr="
Usage: $(basename "$0") {{ option }}

All options: --generate_image --initialize --new --copy --move --run --delete --backup --list 
            --ssh --vnc --smb-follow-symlink --kill --config --establish_dirs 
            --install --help

Tldr:
  1. Create an vm from an iso:
      $(basename "$0") --new image_name --iso_name arch --boot_type efi --ssh_port 2222 --vnc_port 5900 --ram 4 --cpus 4 --cores 4

  2. Delete a vm image:
      $(basename "$0") --delete image_name

  3. List active vms:
      $(basename "$0") --list

  4. List all vms:
      $(basename "$0") --list --all

  5. Kill vm:
      $(basename "$0") {{ image_name }}
      $(basename "$0") --pid {{ pid }}

  6. Start ssh or vnc to an active vm:
      $(basename "$0") --ssh {{ image_name }}
      $(basename "$0") --vnc {{ image_name }}
"

  declare -r complete_options="
Usage: $(basename "$0") {{ option }}

Options:

      -g|--generate_image: create new vm image named {{ image_name }}
          $(basename "$0") -g image_name image_size
        
          defaults:
              image_size  : 4GB

      -i|--initialize: initialize vm image named {{ image_name }} with {{ iso_name }}
          $(basename "$0") -i image_name --iso_name arch --boot_type

          necessary: image_name, --iso_name
          defaults:
              --boot_type     : efi
              --ssh_port      : 2222
              --vnc_port      : 5900
              --image_size    : 4GB
              --ram           : 4GB
              --cpus          : 4
              --cores         : 4
              --ssh_user_name : no default

      -n|--new|--setup: create and initialize vm image named {{ image_name }} with {{ iso_name }}
          $(basename "$0") -n image_name --iso_name arch --image_size 4 --boot_type efi

          necessary: image_name, --iso_name
          defaults:
              same as initialize option (see above)

      -x|--xerox|--copy: copy vm image
          $(basename "$0") -c image_name

      -m|--move: mv vm image (rename)
          $(basename "$0") -m image_name

      -r|--run: run image provided in {{ image_name }}
          $(basename "$0") -r image_name

      -d|--delete: backup vm image or config
          delete vm image:
          $(basename "$0") -d image_name

          delete vm image and backup too:
          $(basename "$0") -d -a image_name

      -l|--list: list active vm images or all vm images
          list active vm images:
            $(basename "$0") -l

          list all vm images:
            $(basename "$0") -l -a

      -b|--backup: backup vm image or config
          $(basename "$0") -b image_name
          $(basename "$0") -b -c

      -s|--ssh: ssh into currently running image
          $(basename "$0") -s image_name user_name

          defaluts:
            user_name: $USER

      -v|--vnc: attach tiger-vnc client to vm
          $(basename "$0") -v image_name

      -f|--smb_follow_symlinks: allow following symlinks in shared directory
          $(basename "$0") -f

          note: can be a security risk

      -k|--kill: kill vm with given {{ image_name }} {{ pid }} or all the vms
          $(basename "$0") -k image_name
          $(basename "$0") -k -p pid
          $(basename "$0") -k -a

      -c|--config: add config for vm image
          $(basename "$0") -a image_name --boot_type efi --ssh_port 2222 --vnc_port 5900

          necessary: image_name
          defaults:
              --boot_type     : efi
              --ssh_port      : 2222
              --vnc_port      : 5900
              --ram           : 4GB
              --cpus          : 4
              --cores         : 4
              --ssh_user_name : no default

          print config if exists:
          $(basename "$0") -a -p image_name

          overwrite config if already exists:
          $(basename "$0") -a -m image_name --boot_type legacy

          delete config if exists:
          $(basename "$0") -a -d image_name

          open config file:
          $(basename "$0") -a -o

      -e|--establish_dirs: make or remove directories required for this script
          make directories:
          $(basename "$0") -e

          remove directories:
          $(basename "$0") -e -r

      -z|--install: install or uninstall script
          install:
          $(basename "$0") -z

          uninstall:
          $(basename "$0") -z -u

      -u|--bash_completion: setup bash completion for this script
          $(basename "$0") -u

      -h|--help: print this help page

defaults for dirs (change in script):

  ovmf file: /usr/share/edk2-ovmf/x64
  isos of os(es): ${HOME}/Downloads/isos

  config directory for vms: ${HOME}/.config/vm
  config file for vms: ${HOME}/.config/vm/config.vm
  images of vms: ${HOME}/.config/vm/images
  ovmf vars for each vm: ${HOME}/.config/vm/ovmf
  backup folder: ${HOME}/.config/vm/backup

  samba share directory: ${HOME}/shared
"
  if [[ "$full_help" == "-a" || "$full_help" == "--all" ]]; then
    echo "$complete_options"
  else
    echo "$tldr"
  fi
}

main()
{
  case "$1" in
    -g | --generate_image)
      declare -r image_name="$2"
      declare -r image_size="$3"
      generate_image_vm "$image_name" "$image_size"
      ;;
    -i | --initialize)
      declare -r image_name="$2"
      declare -A vm_image_config
      vm_image_config[image_name]="$image_name"

      take_config_args_vm vm_image_config "$@"
      initialize_vm vm_image_config
      ;;
    -n | --new | --setup)
      declare -r image_name="$2"
      declare -A vm_image_config
      vm_image_config[image_name]="$image_name"

      take_config_args_vm vm_image_config "$@"
      setup_vm vm_image_config
      ;;
    -x | --xerox | --copy)
      copy_vm "$@"
      ;;
    -m | --move)
      move_vm "$@"
      ;;
    -r | --run)
      run_vm "$@"
      ;;
    -d | --delete)
      delete_vm "$@"
      ;;
    -b | --backup)
      backup_vm "$@"
      ;;
    -l | --list)
      list_vm "$@"
      ;;
    -s | --ssh)
      ssh_vm "$@"
      ;;
    -v | --vnc)
      vnc_vm "$@"
      ;;
    -f | --smb_follow_symlinks)
      qemu_smb_support_symlink_all_vm
      ;;
    -k | --kill)
      kill_vm "$@"
      ;;
    -c | --config)
      # shellcheck disable=2034
      declare -A vm_image_config
      take_config_args_vm vm_image_config "$@"
      config_vm vm_image_config "$@"
      ;;
    -e | --establish_dirs)
      establish_dirs_vm "$@"
      ;;
    -z | --install)
      install_vm "$@"
      ;;
    -u | --bash_completion)
      setup_bash_completion_vm
      ;;
    -h | --help)
      help_vm "$@"
      ;;
    *) echo "$(basename "$0"): arg $1 not supported" ;;
  esac
}

main "$@"
